//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIVIT.CIPA.Api.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIVIT.Exper.Api.Domain.Resources.EnumDescription", typeof(EnumDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        internal static string BscIndicatorApuration_Area {
            get {
                return ResourceManager.GetString("BscIndicatorApuration_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geral.
        /// </summary>
        internal static string BscIndicatorApuration_General {
            get {
                return ResourceManager.GetString("BscIndicatorApuration_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string BscIndicatorApuration_Individual {
            get {
                return ResourceManager.GetString("BscIndicatorApuration_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string BscIndicatorDimension_Customer {
            get {
                return ResourceManager.GetString("BscIndicatorDimension_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financeiro.
        /// </summary>
        internal static string BscIndicatorDimension_Financial {
            get {
                return ResourceManager.GetString("BscIndicatorDimension_Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoas.
        /// </summary>
        internal static string BscIndicatorDimension_People {
            get {
                return ResourceManager.GetString("BscIndicatorDimension_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos.
        /// </summary>
        internal static string BscIndicatorDimension_Process {
            get {
                return ResourceManager.GetString("BscIndicatorDimension_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimestral.
        /// </summary>
        internal static string BscIndicatorFrequency_Bimonthly {
            get {
                return ResourceManager.GetString("BscIndicatorFrequency_Bimonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensal.
        /// </summary>
        internal static string BscIndicatorFrequency_Monthly {
            get {
                return ResourceManager.GetString("BscIndicatorFrequency_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestral.
        /// </summary>
        internal static string BscIndicatorFrequency_Quarterly {
            get {
                return ResourceManager.GetString("BscIndicatorFrequency_Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestral Comercial.
        /// </summary>
        internal static string BscIndicatorFrequency_QuarterlyCommercial {
            get {
                return ResourceManager.GetString("BscIndicatorFrequency_QuarterlyCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestral.
        /// </summary>
        internal static string BscIndicatorFrequency_Semiannual {
            get {
                return ResourceManager.GetString("BscIndicatorFrequency_Semiannual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestral Comercial.
        /// </summary>
        internal static string BscIndicatorFrequency_SemiannualCommercial {
            get {
                return ResourceManager.GetString("BscIndicatorFrequency_SemiannualCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual.
        /// </summary>
        internal static string BscIndicatorFrequency_Yearly {
            get {
                return ResourceManager.GetString("BscIndicatorFrequency_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual Comercial.
        /// </summary>
        internal static string BscIndicatorFrequency_YearlyCommercial {
            get {
                return ResourceManager.GetString("BscIndicatorFrequency_YearlyCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automático.
        /// </summary>
        internal static string BscIndicatorItemType_Automatic {
            get {
                return ResourceManager.GetString("BscIndicatorItemType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string BscIndicatorItemType_Manual {
            get {
                return ResourceManager.GetString("BscIndicatorItemType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quanto maior melhor.
        /// </summary>
        internal static string BscIndicatorNature_BiggerBetter {
            get {
                return ResourceManager.GetString("BscIndicatorNature_BiggerBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quanto menor melhor.
        /// </summary>
        internal static string BscIndicatorNature_SmallerBetter {
            get {
                return ResourceManager.GetString("BscIndicatorNature_SmallerBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias.
        /// </summary>
        internal static string BscIndicatorTargetUnit_Days {
            get {
                return ResourceManager.GetString("BscIndicatorTargetUnit_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês.
        /// </summary>
        internal static string BscIndicatorTargetUnit_Month {
            get {
                return ResourceManager.GetString("BscIndicatorTargetUnit_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual.
        /// </summary>
        internal static string BscIndicatorTargetUnit_Percentage {
            get {
                return ResourceManager.GetString("BscIndicatorTargetUnit_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string BscIndicatorTargetUnit_Value {
            get {
                return ResourceManager.GetString("BscIndicatorTargetUnit_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês Apuração.
        /// </summary>
        internal static string BscIndicatorValueCategory_ApurationMonth {
            get {
                return ResourceManager.GetString("BscIndicatorValueCategory_ApurationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média.
        /// </summary>
        internal static string BscIndicatorValueCategory_Average {
            get {
                return ResourceManager.GetString("BscIndicatorValueCategory_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soma.
        /// </summary>
        internal static string BscIndicatorValueCategory_Sum {
            get {
                return ResourceManager.GetString("BscIndicatorValueCategory_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Acompanhamento.
        /// </summary>
        internal static string BscPanelStatus_InProgress {
            get {
                return ResourceManager.GetString("BscPanelStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Revisão.
        /// </summary>
        internal static string BscPanelStatus_InReview {
            get {
                return ResourceManager.GetString("BscPanelStatus_InReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivos a Serem Criados.
        /// </summary>
        internal static string BscPanelStatus_TargetToBeCreated {
            get {
                return ResourceManager.GetString("BscPanelStatus_TargetToBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Custo.
        /// </summary>
        internal static string BscServiceLineType_CostCenter {
            get {
                return ResourceManager.GetString("BscServiceLineType_CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torre.
        /// </summary>
        internal static string BscServiceLineType_Tower {
            get {
                return ResourceManager.GetString("BscServiceLineType_Tower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSC.
        /// </summary>
        internal static string CycleType_Bsc {
            get {
                return ResourceManager.GetString("CycleType_Bsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDI.
        /// </summary>
        internal static string CycleType_Pdi {
            get {
                return ResourceManager.GetString("CycleType_Pdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compêtencias.
        /// </summary>
        internal static string CycleType_Skills {
            get {
                return ResourceManager.GetString("CycleType_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent Pool.
        /// </summary>
        internal static string CycleType_TalentPool {
            get {
                return ResourceManager.GetString("CycleType_TalentPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado.
        /// </summary>
        internal static string PdiPanelStatus_Completed {
            get {
                return ResourceManager.GetString("PdiPanelStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Preparação.
        /// </summary>
        internal static string PdiPanelStatus_InPreparation {
            get {
                return ResourceManager.GetString("PdiPanelStatus_InPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Andamento.
        /// </summary>
        internal static string PdiPanelStatus_InProgress {
            get {
                return ResourceManager.GetString("PdiPanelStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Aprovação.
        /// </summary>
        internal static string PdiPanelStatus_OnApproval {
            get {
                return ResourceManager.GetString("PdiPanelStatus_OnApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSC.
        /// </summary>
        internal static string PlrType_Bsc {
            get {
                return ResourceManager.GetString("PlrType_Bsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent Pool.
        /// </summary>
        internal static string PlrType_TalentPool {
            get {
                return ResourceManager.GetString("PlrType_TalentPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apurado.
        /// </summary>
        internal static string TalentApuredStatus_Apured {
            get {
                return ResourceManager.GetString("TalentApuredStatus_Apured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Apurado.
        /// </summary>
        internal static string TalentApuredStatus_NotApured {
            get {
                return ResourceManager.GetString("TalentApuredStatus_NotApured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não apurado justificado ADM.
        /// </summary>
        internal static string TalentApuredStatus_NotApuredJustified {
            get {
                return ResourceManager.GetString("TalentApuredStatus_NotApuredJustified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não apurado justificado ausência.
        /// </summary>
        internal static string TalentApuredStatus_NotApuredJustifiedAbsence {
            get {
                return ResourceManager.GetString("TalentApuredStatus_NotApuredJustifiedAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não apurado justificado férias.
        /// </summary>
        internal static string TalentApuredStatus_NotApuredJustifiedVacation {
            get {
                return ResourceManager.GetString("TalentApuredStatus_NotApuredJustifiedVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        internal static string TalentIndicatorApprovalStatus_Approved {
            get {
                return ResourceManager.GetString("TalentIndicatorApprovalStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente aprovação da área de Talent Pool.
        /// </summary>
        internal static string TalentIndicatorApprovalStatus_Pending {
            get {
                return ResourceManager.GetString("TalentIndicatorApprovalStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovado.
        /// </summary>
        internal static string TalentIndicatorApprovalStatus_Reject {
            get {
                return ResourceManager.GetString("TalentIndicatorApprovalStatus_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIVIT Brasil.
        /// </summary>
        internal static string TalentIndicatorCompany_TIVITBrasil {
            get {
                return ResourceManager.GetString("TalentIndicatorCompany_TIVITBrasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIVIT Latam.
        /// </summary>
        internal static string TalentIndicatorCompany_TIVITLatam {
            get {
                return ResourceManager.GetString("TalentIndicatorCompany_TIVITLatam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        internal static string TalentIndicatorCountry_Argentina {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia.
        /// </summary>
        internal static string TalentIndicatorCountry_Bolivia {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brasil.
        /// </summary>
        internal static string TalentIndicatorCountry_Brasil {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Brasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        internal static string TalentIndicatorCountry_Chile {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        internal static string TalentIndicatorCountry_Colombia {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equador.
        /// </summary>
        internal static string TalentIndicatorCountry_Equador {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Equador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        internal static string TalentIndicatorCountry_Mexico {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        internal static string TalentIndicatorCountry_Panama {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguai.
        /// </summary>
        internal static string TalentIndicatorCountry_Paraguai {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Paraguai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string TalentIndicatorCountry_Peru {
            get {
                return ResourceManager.GetString("TalentIndicatorCountry_Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string TalentIndicatorDimension_Customer {
            get {
                return ResourceManager.GetString("TalentIndicatorDimension_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financeiro.
        /// </summary>
        internal static string TalentIndicatorDimension_Financial {
            get {
                return ResourceManager.GetString("TalentIndicatorDimension_Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoas.
        /// </summary>
        internal static string TalentIndicatorDimension_People {
            get {
                return ResourceManager.GetString("TalentIndicatorDimension_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos.
        /// </summary>
        internal static string TalentIndicatorDimension_Process {
            get {
                return ResourceManager.GetString("TalentIndicatorDimension_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimestral.
        /// </summary>
        internal static string TalentIndicatorFrequency_Bimonthly {
            get {
                return ResourceManager.GetString("TalentIndicatorFrequency_Bimonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensal.
        /// </summary>
        internal static string TalentIndicatorFrequency_Monthly {
            get {
                return ResourceManager.GetString("TalentIndicatorFrequency_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestral.
        /// </summary>
        internal static string TalentIndicatorFrequency_Quarterly {
            get {
                return ResourceManager.GetString("TalentIndicatorFrequency_Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestral.
        /// </summary>
        internal static string TalentIndicatorFrequency_Semiannual {
            get {
                return ResourceManager.GetString("TalentIndicatorFrequency_Semiannual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual.
        /// </summary>
        internal static string TalentIndicatorFrequency_Yearly {
            get {
                return ResourceManager.GetString("TalentIndicatorFrequency_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatico.
        /// </summary>
        internal static string TalentIndicatorItemType_Automatic {
            get {
                return ResourceManager.GetString("TalentIndicatorItemType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string TalentIndicatorItemType_Manual {
            get {
                return ResourceManager.GetString("TalentIndicatorItemType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quanto maior melhor.
        /// </summary>
        internal static string TalentIndicatorNature_BiggerBetter {
            get {
                return ResourceManager.GetString("TalentIndicatorNature_BiggerBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quanto menor melhor.
        /// </summary>
        internal static string TalentIndicatorNature_SmallerBetter {
            get {
                return ResourceManager.GetString("TalentIndicatorNature_SmallerBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias.
        /// </summary>
        internal static string TalentIndicatorTargetUnit_Days {
            get {
                return ResourceManager.GetString("TalentIndicatorTargetUnit_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas.
        /// </summary>
        internal static string TalentIndicatorTargetUnit_Hours {
            get {
                return ResourceManager.GetString("TalentIndicatorTargetUnit_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        internal static string TalentIndicatorTargetUnit_Others {
            get {
                return ResourceManager.GetString("TalentIndicatorTargetUnit_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual.
        /// </summary>
        internal static string TalentIndicatorTargetUnit_Percentual {
            get {
                return ResourceManager.GetString("TalentIndicatorTargetUnit_Percentual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        internal static string TalentIndicatorTargetUnit_Quantity {
            get {
                return ResourceManager.GetString("TalentIndicatorTargetUnit_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string TalentIndicatorTargetUnit_Value {
            get {
                return ResourceManager.GetString("TalentIndicatorTargetUnit_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        internal static string TalentPanelApprovalStatus_Approved {
            get {
                return ResourceManager.GetString("TalentPanelApprovalStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovado.
        /// </summary>
        internal static string TalentPanelApprovalStatus_Reject {
            get {
                return ResourceManager.GetString("TalentPanelApprovalStatus_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Acompanhamento.
        /// </summary>
        internal static string TalentPanelStatus_InProgress {
            get {
                return ResourceManager.GetString("TalentPanelStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Revisão.
        /// </summary>
        internal static string TalentPanelStatus_InReview {
            get {
                return ResourceManager.GetString("TalentPanelStatus_InReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente aprovação do Líder.
        /// </summary>
        internal static string TalentPanelStatus_Pending {
            get {
                return ResourceManager.GetString("TalentPanelStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovado.
        /// </summary>
        internal static string TalentPanelStatus_Reject {
            get {
                return ResourceManager.GetString("TalentPanelStatus_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivos a Serem Criados.
        /// </summary>
        internal static string TalentPanelStatus_TargetToBeCreated {
            get {
                return ResourceManager.GetString("TalentPanelStatus_TargetToBeCreated", resourceCulture);
            }
        }
    }
}
